version: "3.8"

services:
  api:
    build:
      context: "./workspaces/server"
    ports:
      - 3002:3002
    external_links:
      - mongo
    volumes:
      - ./volumes/files:/app/files
    restart: on-failure:5

  mongo:
    container_name: mongo
    image: mongo:5.0.5
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodata:/data/db
    restart: on-failure:5

  static:
    depends_on:
      - api
    build:
      context: ./workspaces/static
    ports:
      - 3000:80
    restart: on-failure:5
